// Package markdown provides parsing and serialization of Obsidian-compatible
// markdown files with YAML frontmatter for the markedup knowledge graph.
package markdown

import (
	"fmt"
	"io"
	"os"
	"regexp"
	"strings"

	"github.com/KHAEntertainment/markedup/schema"
	"gopkg.in/yaml.v3"
)

// frontmatterRe matches YAML frontmatter delimited by --- on their own lines.
// Group 1 captures the YAML content, group 2 captures everything after.
var frontmatterRe = regexp.MustCompile(`(?s)\A\s*---\n(.+?)\n---\n?(.*)`)

// ParseFile reads a markdown file from disk and returns a parsed Page.
// The returned Page's SourcePath is set to the given path.
func ParseFile(path string) (*schema.Page, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("markdown: read file %s: %w", path, err)
	}
	page, err := ParseBytes(data)
	if err != nil {
		return nil, err
	}
	page.SourcePath = path
	return page, nil
}

// ParseReader reads all bytes from r and returns a parsed Page.
func ParseReader(r io.Reader) (*schema.Page, error) {
	data, err := io.ReadAll(r)
	if err != nil {
		return nil, fmt.Errorf("markdown: read: %w", err)
	}
	return ParseBytes(data)
}

// ParseBytes parses raw markdown bytes into a Page. The input must contain
// YAML frontmatter delimited by --- on their own lines.
func ParseBytes(data []byte) (*schema.Page, error) {
	matches := frontmatterRe.FindSubmatch(data)
	if matches == nil {
		return nil, fmt.Errorf("markdown: no valid frontmatter found")
	}

	var fm schema.GraphFrontmatter
	if err := yaml.Unmarshal(matches[1], &fm); err != nil {
		return nil, fmt.Errorf("markdown: unmarshal frontmatter: %w", err)
	}

	body := strings.TrimSpace(string(matches[2]))

	// Strip leading H1 if it matches the frontmatter title (generated by serializer).
	if fm.Title != "" {
		h1Prefix := "# " + fm.Title
		if body == h1Prefix || strings.HasPrefix(body, h1Prefix+"\n") {
			body = strings.TrimSpace(strings.TrimPrefix(body, h1Prefix))
		}
	}

	return &schema.Page{
		Frontmatter: fm,
		Body:        body,
	}, nil
}
